# Generated by Django 5.1.6 on 2025-04-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0002_foodmenu_foodshare_fooditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodshare',
            old_name='text',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='hours',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodshare',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='burghy.user'),
            preserve_default=False,
        ),
    ]
