# Generated by Django 5.1.6 on 2025-04-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0003_rename_text_foodshare_desc_foodmenu_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodshare',
            name='pfp',
            field=models.ImageField(default='https://avatar.iran.liara.run/public', upload_to=''),
            preserve_default=False,
        ),
    ]
