# Generated by Django 5.1.6 on 2025-04-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0004_foodshare_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
