# Generated by Django 5.1.7 on 2025-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0005_foodmenu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPleaseWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('hours', models.CharField(max_length=20)),
            ],
        ),
    ]
