# Generated by Django 5.1.6 on 2025-04-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0007_menupleasework_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupleasework',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
