# Generated by Django 5.1.6 on 2025-05-15 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0008_alter_menupleasework_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=20)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burghy.foodlocation'),
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burghy.user')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodShare',
        ),
        migrations.DeleteModel(
            name='FoodMenu',
        ),
    ]
