# Generated by Django 5.1.7 on 2025-05-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0008_alter_menupleasework_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodshare',
            old_name='title',
            new_name='postedAt',
        ),
        migrations.RenameField(
            model_name='foodshare',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='foodshare',
            name='comments',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodshare',
            name='likes',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodshare',
            name='tags',
            field=models.JSONField(default=['free']),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodshare',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
