# Generated by Django 5.1.7 on 2025-05-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0009_rename_title_foodshare_postedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodshare',
            name='pfp',
            field=models.CharField(max_length=50),
        ),
    ]
