# Generated by Django 5.1.6 on 2025-05-15 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0010_delete_menupleasework_alter_foodlocation_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='desc',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='pfp',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='title',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Unnamed', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.CharField(default='https://avatar.iran.liara.run/public', max_length=150),
        ),
        migrations.AddField(
            model_name='userpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='burghy.user'),
            preserve_default=False,
        ),
    ]
