# Generated by Django 5.1.7 on 2025-05-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0010_alter_foodshare_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodshare',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foodshare',
            name='pfp',
            field=models.CharField(max_length=100),
        ),
    ]
