# Generated by Django 5.1.6 on 2025-05-15 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0011_rename_desc_userpost_content_remove_userpost_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('swipe', 'Meal Swipe'), ('dining_dollars', 'Dining Dollars'), ('cardinal_cash', 'Cardinal Cash'), ('credit_card', 'Credit Card')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='burghy.foodlocation')),
            ],
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('choices', models.JSONField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='burghy.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_payments', to='burghy.menuitem')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burghy.paymentmethod')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
