# Generated by Django 5.1.7 on 2025-05-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0011_alter_foodshare_image_alter_foodshare_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodshare',
            name='tags',
            field=models.CharField(max_length=20),
        ),
    ]
