# Generated by Django 5.1.6 on 2025-05-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0012_paymentmethod_menuitem_menuoption_allowedpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='AllowedPayment',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
