# Generated by Django 5.1.7 on 2025-05-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0012_alter_foodshare_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodshare',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
