# Generated by Django 5.1.7 on 2025-05-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0013_alter_foodshare_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodshare',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
