# Generated by Django 5.1.6 on 2025-05-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0013_alter_userpost_image_delete_allowedpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='meal_swipe_elegible',
            field=models.BooleanField(default=False),
        ),
    ]
