# Generated by Django 5.1.7 on 2025-05-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0014_alter_foodshare_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodshare',
            name='tags',
        ),
    ]
