# Generated by Django 5.1.6 on 2025-05-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0014_menuitem_meal_swipe_elegible'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='burghy.user'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='burghy.userpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burghy.user')),
            ],
        ),
    ]
