# Generated by Django 5.1.7 on 2025-05-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0015_remove_foodshare_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodshare',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
