# Generated by Django 5.1.7 on 2025-05-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burghy', '0016_alter_foodshare_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodshare',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
